### ISSUE TITLE
[Compat] Allow Chiseled armour to render when worn by Custom NPCs

### ISSUE THREAD

**Issue by thephoenixlodge** [Phylogeny/ExtraBitManipulation#17]
Currently placing chiseled armour in a an NPCs armour slots won't render it on the NPC. After speaking with Noppes (author of CNPCs), it's apparently a matter of allowing the armour to render on zombies.

**Comment by Phylogeny** [comment]
Vanilla zombies? Because it should render on them already (if it doesn't for you, let me know). If so, not only does that indicate it should already work, but it seems odd to me that it would; chiseled armor is rendered via a [render layer](https://github.com/Phylogeny/ExtraBitManipulation/blob/1.12/src/main/java/com/phylogeny/extrabitmanipulation/armor/LayerChiseledArmor.java) that is [separately added to the renderers of specific entity classes registered with the render manager](https://github.com/Phylogeny/ExtraBitManipulation/blob/1.12/src/main/java/com/phylogeny/extrabitmanipulation/init/RenderLayersExtraBitManipulation.java#L33). Unless he's importing copies of the render layers of the vanilla zombie class's renderer, I don't see how merely rendering on vanilla zombies would cause rendering on his entities.

If not, I don't see anything in CustomNPCsAPI for adding render layers to any of his entities, and his mod is closed source.

**Comment by KathySharks** [comment]
Well, a bit of fiddling revealed the following behaviour. [Tested in 1.12.2 most recent Forge]
![image](https://user-images.githubusercontent.com/32834019/31603719-022b7e70-b22f-11e7-8bbd-8b00f5ba3f86.png)


Under the guise of typical mobs it works fine, but not the default NPC entity. Because the default NPC entity isn't working, the Puppet 'job' implemented by CustomNPCs (Which allows the pose seen above), does not apply to mobs and therefor does not allow one to pose them while wearing Chiseled Armor.

It seems that the NPC entity from Custom NPCs, is not referred to as Zombie internally.
My guess is that it's another entity referred to in the API.

Contacting Noppes directly may yield better answers. I've opened an issue on the mod's curseforge page. [https://minecraft.curseforge.com/projects/custom-npcs/issues/1926](url)

**Comment by Phylogeny** [comment]
This should be fixed as of [v3.3.0](https://minecraft.curseforge.com/projects/extra-bit-manipulation/files/2599912). Let me know if you run into any problems.
