### ISSUE TITLE
Server forsed to shutdown, 1.10.2 - MalisisDoors v5.1.4

### ISSUE THREAD

**Issue by Dushess** [Phylogeny/ExtraBitManipulation#7]
During world loading, and then game crashing.
All in the log, and sorry for wall of text, some unrelated model problems, not messing with game process.
latest version is from [AlgorithmX2/Chisels-and-Bits#160](https://github.com/AlgorithmX2/Chisels-and-Bits/issues/160)

[fml-client-latest.txt](https://github.com/Phylogeny/ExtraBitManipulation/files/600987/fml-client-latest.txt)

**Comment by Phylogeny** [comment]
There is no indication anywhere in that log that EBM has anything to do with the crash.

**Comment by Dushess** [comment]
BUT, game crashes with this mod, confirmed.

**Comment by Phylogeny** [comment]
There are 136 references to EBM in that log. I've gone through and looked at every one for a second time over, and every single reference is completely normal.

As for the stack trace, EntityRenderer.updateFogColor is getting a null entity from Minecraft.getRenderViewEntity and passing it to World.getSkyColor, which is causing an NPE. Why that is happening, I have no idea.

Again there is simply no indication of EBM having anything to do with that crash. If somehow, despite no evidence in the log, it really is EBM causing the crash, hopefully the update I will be releasing shortly for the 1.8.9, 1.9.4, and 1.10.2 versions will have somehow fixed it, since I no longer use the capability system in the new update (if that was somehow the problem).

**Comment by Dushess** [comment]
I will try only C&B and EBM.

Yeah, other mod dependency, checking...

## MalisisDoors v5.1.4
